name: Build DLL Injector GUI EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./QT/requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --windowed ./QT/dll-injector-gui.py

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dll-injector-gui-exe
        path: ./dist/dll-injector-gui.exe
